name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0
      - run: dotnet --info
      - name: Build / Test / Pack
        env:
          DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
          TERM: xterm
        run: pwsh ./eng/pack.ps1
      - name: Release to MyGet
        env:
          PACKAGE_URL: https://www.myget.org/F/parsley-ci/api/v3/index.json
          PACKAGE_API_KEY: ${{ secrets.MYGET_API_KEY }}
        run: pwsh ./eng/release.ps1