name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0
      - name: Build / Test / Pack
        run: pwsh ./eng/pack.ps1
      - name: Release to NuGet
        env:
          PACKAGE_URL: https://api.nuget.org/v3/index.json
          PACKAGE_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: pwsh ./eng/release.ps1