name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0
      - run: dotnet --info
      - name: Build
        env:
          DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
          TERM: xterm
        run: pwsh ./build --pack
      - name: Release to NuGet
        env:
          PACKAGE_URL: https://api.nuget.org/v3/index.json
          PACKAGE_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: pwsh ./release.ps1